{Build} Enhance build stability (#164)
Summary:
Pull Request resolved: https://github.com/facebookresearch/vrs/pull/164

- Better support recent fmt library update
  - `fmt::join` needs an include

- Better support of CMake install
  - vrs_utils_cli needs to be installed

- VrsPlayer is Thread dependent
  - need to be linked to Threads

- Linux `rt` library is required
  - to fix `undefined reference to aio_write` & `undefined reference to aio_return` on some distributions

- `lz4` and `zstd` does not need to leak to client (only used in cpp)
  - they can be linked privately

Reviewed By: georges-berenger

Differential Revision: D62672156

fbshipit-source-id: 1f63b292fa6ff74683c024f9b7b9a65c7b4d5bd0