{Build} Enhance build stability
Summary:
- Better support recent fmt library update
  - `fmt::join` needs an include

- Better support of CMake install
  - vrs_utils_cli needs to be installed

- VrsPlayer is Thread dependent
  - need to be linked to Threads

- Linux `rt` library is required
  - to fix `undefined reference to aio_write` & `undefined reference to aio_return` on some distributions

- `lz4` and `zstd` does not need to leak to client (only used in cpp)
  - they can be linked privately

Differential Revision: D62672156