{Build} Fix macos GitHub worfklow (#213)
Summary:
Pull Request resolved: https://github.com/facebookresearch/vrs/pull/213

Summary of the encountered errors -- only on Mac GitHub runners:

## Homebrew version update -- creating an issue with CMake installation

Reported log issue:
```
Error: cmake was installed from the local/pinned tap
but you are trying to install it from the homebrew/core tap.
Formulae with the same name from different taps cannot be installed at the same time.
```

Solution:
- Use existing GitHub runner images Git and Ninja - so we avoid this Error
- Force update CMake to have CMake >= 4

## Homebrew now install `Boost-1.89.0` -- system is now header only

Reported log issue:
```
Could not find a package configuration file provided by "boost_system"
```

Solution:
- Boost.system is now a header only library and we don't need to "link" to it (https://github.com/boostorg/system/issues/132#issuecomment-3146378680)

Reviewed By: georges-berenger

Differential Revision: D81600728

fbshipit-source-id: 9f2d25900e1ba25e6b02edd105d102a359f6a8eb