Fix compile error
Summary:
Failed to build with either `arvr/mode/win/opt` or `/arvr/mode/win/vs2022/cpp20/opt` with `error C2065: 'tuple': undeclared identifier`. I'm not sure what change would have caused this to break or how it would have gotten past CI. But seems like a very straight forward error and fix.

Error was on the declaration:

```
map<tuple<StreamId, Record::Type, uint32_t>, RecordFormatReader> readers_;
```

Header uses `tuple` and should therefore include `tuple`. Header also uses `pair` on `map<pair<StreamId, Record::Type>, RecordFormatReader*> lastReader_;` so I added `using std::pair` for good measure.

Reviewed By: georges-berenger

Differential Revision: D72348966

fbshipit-source-id: 382b2a42f2653d970c41aebda132f65a9c02e658