Fix enum-enum conversion issue in vrsplayer (#134)
Summary:
Pull Request resolved: https://github.com/facebookresearch/vrs/pull/134

static_cast<int>(enum) before bit wise or. This should resolve the -Wdeprecated-enum-enum-conversion warning and thus won't need to ignore this warning in this library.

Fixing this will also ensure build-calibration-cpp20 will pass.

```
buck build arvr/mode/platform010/c++20/opt-stripped //arvr/libraries/vrs/oss/tools/vrsplayer:vrsplayerlib
arvr/libraries/vrs/oss/tools/vrsplayer/PlayerWindow.cpp:91:36: error: bitwise operation between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
  saveFrames->setShortcut(Qt::CTRL | Qt::Key_S);
                          ~~~~~~~~ ^ ~~~~~~~~~
arvr/libraries/vrs/oss/tools/vrsplayer/PlayerWindow.cpp:146:42: error: bitwise operation between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
      recallAction->setShortcut(Qt::CTRL | static_cast<Qt::Key>(Qt::Key_0 + number));
                                ~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arvr/libraries/vrs/oss/tools/vrsplayer/PlayerWindow.cpp:200:37: error: bitwise operation between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
  smallerFont->setShortcut(Qt::CTRL | Qt::Key_Minus);
                           ~~~~~~~~ ^ ~~~~~~~~~~~~~
arvr/libraries/vrs/oss/tools/vrsplayer/PlayerWindow.cpp:204:37: error: bitwise operation between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
  largestFont->setShortcut(Qt::CTRL | Qt::Key_Plus);
                           ~~~~~~~~ ^ ~~~~~~~~~~~~
arvr/libraries/vrs/oss/tools/vrsplayer/PlayerWindow.cpp:215:41: error: bitwise operation between different enumeration types ('Qt::Modifier' and 'Qt::Key') is deprecated [-Werror,-Wdeprecated-enum-enum-conversion]
  solidBackground->setShortcut(Qt::CTRL | Qt::Key_B);
                               ~~~~~~~~ ^ ~~~~~~~~~
```

Reviewed By: jhouben-fb

Differential Revision: D49025282

fbshipit-source-id: dea916a8d40ee4218448188a09fed43558156d21