fix build failure
Summary:
Building VRS on windows is causing a build failure
```
C:\open\fbsource\arvr\libraries\vrs\vrs\ProgressLogger.h(136): error C2220: the following warning is treated as an error
C:\open\fbsource\arvr\libraries\vrs\vrs\ProgressLogger.h(136): warning C4100: 'precision': unreferenced formal parameter
C:\open\fbsource\arvr\libraries\vrs\vrs\ProgressLogger.h(136): warning C4100: 'duration': unreferenced formal parameter
C:\open\fbsource\arvr\libraries\vrs\vrs\ProgressLogger.h(136): warning C4100: 'operationName': unreferenced formal parameter
```

Reviewed By: georges-berenger

Differential Revision: D53843146

fbshipit-source-id: 5a7b8500f52f184ed2b129155cbe899bc4e9cf3a