{Build} Fix macos GitHub worfklow (#213)
Summary:

Summary of the encountered error:
```
Error: cmake was installed from the local/pinned tap
but you are trying to install it from the homebrew/core tap.
Formulae with the same name from different taps cannot be installed at the same time.
```

Solution:
- Use existing GitHub runner images Git and Ninja - so we avoid this Error
- Force update CMake to have CMake >= 4

Then another issue appears with BOOST being updated to `Boost-1.89.0` on mac
```
Could not find a package configuration file provided by "boost_system"
```

Solution:
- Boost.system is now a header only library and we don't need to "link" to it (https://github.com/boostorg/system/issues/132#issuecomment-3146378680)

Differential Revision: D81600728