{Build} Fix fmt includes -- fmt 11 and forward
Summary:
mac-latest on GitHub CI is not shipping with fmt 11 and some include path have changed.
We are fixing here the default include in our library to be compatible with the new version and also backward compatible.

Here the failure message on GitHub actions:

```
FAILED: [code=1] vrs/helpers/CMakeFiles/vrs_helpers.dir/Throttler.cpp.o
/usr/bin/c++ -DFMT_SHARED -DOSS_BUILD_MODE -I/Users/runner/work/vrs/vrs -I/Users/runner/work/vrs/vrs/vrs/oss -isystem /opt/homebrew/include -isystem /Users/runner/work/vrs/vrs/build/external/rapidjson/include -O3 -DNDEBUG -std=c++17 -arch arm64 -fPIC -MD -MT vrs/helpers/CMakeFiles/vrs_helpers.dir/Throttler.cpp.o -MF vrs/helpers/CMakeFiles/vrs_helpers.dir/Throttler.cpp.o.d -o vrs/helpers/CMakeFiles/vrs_helpers.dir/Throttler.cpp.o -c /Users/runner/work/vrs/vrs/vrs/helpers/Throttler.cpp
/Users/runner/work/vrs/vrs/vrs/helpers/Throttler.cpp:39:7: error: no member named 'format' in namespace 'fmt'
   39 |       XR_LOGW(
      |       ^~~~~~~~
   40 |           "The following condition has happened {} times now, "
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   41 |           "so we will no longer report each new occurrence.",
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   42 |           stats.requestCounter);
      |           ~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vrs/vrs/vrs/oss/logging/Log.h:62:22: note: expanded from macro 'XR_LOGW'
   62 | #define XR_LOGW(...) XR_LOG_DEFAULT(vrs::logging::Level::Warning, __VA_ARGS__)
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vrs/vrs/vrs/oss/logging/Log.h:55:73: note: expanded from macro 'XR_LOG_DEFAULT'
   55 | #define XR_LOG_DEFAULT(level, ...) log(level, DEFAULT_LOG_CHANNEL, fmt::format(__VA_ARGS__))
      |                                                                    ~~~~~^
/Users/runner/work/vrs/vrs/vrs/helpers/Throttler.cpp:44:7: error: no member named 'format' in namespace 'fmt'
   44 |       XR_LOGW(
      |       ^~~~~~~~
   45 |           "The following condition has happened {} times, and we no longer report each occurrence. "
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   46 |           "We skipped {} reports since the last one.",
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   47 |           stats.requestCounter,
      |           ~~~~~~~~~~~~~~~~~~~~~
   48 |           stats.skipSinceLastReport);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vrs/vrs/vrs/oss/logging/Log.h:62:22: note: expanded from macro 'XR_LOGW'
   62 | #define XR_LOGW(...) XR_LOG_DEFAULT(vrs::logging::Level::Warning, __VA_ARGS__)
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/vrs/vrs/vrs/oss/logging/Log.h:55:73: note: expanded from macro 'XR_LOG_DEFAULT'
   55 | #define XR_LOG_DEFAULT(level, ...) log(level, DEFAULT_LOG_CHANNEL, fmt::format(__VA_ARGS__))
      |                                                                    ~~~~~^
2 errors generated.
```

Fix:
- Including <fmt/format.h> is the most compatible way that will work for OLD and NEW versions.
- It's the portable choice because it's existed in every {fmt} release and has always declared fmt::format (it's the canonical header for the full formatting API).

Reviewed By: georges-berenger, Dvad

Differential Revision: D109859743

fbshipit-source-id: 062df16e6f034e195d1dfd88faff28f65e471167